export { createOfficeEngine } from "./engine.js";
export { OfficeEngineError } from "./types.js";
export { evaluateLicense } from "./license.js";
export type {
  LicenseBranding,
  LicenseClaims,
  LicenseEntitlements,
  LicenseOptions,
  LicensePlan,
  LicenseState,
  LicenseStatus,
} from "./license.js";
export type { FormatPack, FormatPackCandidate, FormatPackFactory } from "./format-pack.js";
export type {
  Diagnostic,
  DocumentOutlineItem,
  DiagnosticFidelity,
  DiagnosticPhase,
  DiagnosticSeverity,
  DocumentAction,
  DocumentActionKind,
  DocumentActionTrigger,
  DocumentFormat,
  DocumentFontRun,
  DocumentFontSource,
  DocumentInfo,
  DocumentKind,
  DocumentObject,
  DocumentObjectType,
  EngineOptions,
  FontAsset,
  FontPolicy,
  FontProvider,
  FontProviderContext,
  FontProviderDiagnostic,
  FontProviderDiagnosticCode,
  FontProviderResult,
  FontRequest,
  FontStretch,
  FontStyle,
  HitResult,
  HitTestRequest,
  MappingQuality,
  ObjectListRequest,
  OfficeDocument,
  OfficeEngine,
  OpenOptions,
  Rect,
  RenderOptions,
  RenderPriority,
  RenderRequest,
  RenderResult,
  RenderedTextFragment,
  RenderedMedia,
  ResourceLimits,
  SheetAxis,
  SheetAxisSpan,
  SheetSizeOverride,
  SourceRef,
  TextSearchRequest,
  TextSearchResult,
  UnitDescriptor,
  Viewport,
  WasmSource,
} from "./types.js";
